version: '3.8'

networks:
  staff-network:
    driver: bridge

services:
  frontend:
    image: node:alpine
    build:
      context: ./frontend
      dockerfile: ./frontend/Dockerfile
    volumes: 
      - .:/usr/src/client
    working_dir: /usr/src/client/frontend  
    ports:
      - '3000:3000'    
    networks:
      - staff-network    
    depends_on:
      - api
      - api_mongo  
    entrypoint: [ "/usr/src/client/frontend/wait-for.sh", "api_mongo:27017", "--","/usr/src/client/frontend/start.sh" ]  
    environment:
      - API_ADDR=http://127.0.0.1:3001

  api: 
    image: node:alpine
    build:
      context: ./backend
      dockerfile: ./backend/Dockerfile
    volumes: 
      - .:/usr/src/app
    working_dir: /usr/src/app/backend  
    ports:
      - '3001:3001'  
    networks:
      - staff-network  
    depends_on:
      - api_mongo  
    # command: npm install && migrate-mongo up && node server  
    entrypoint: [ "/usr/src/app/backend/wait-for.sh", "api_mongo:27017", "--", "/usr/src/app/backend/start_for_docker.sh" ]
    environment:
      - MONGO_URL=mongodb://api_mongo:27017/staff

  api_mongo:
    image: mongo:latest
    volumes:
      - mongodb_volume:/data/db
    ports:
      - '27017:27017'
    networks:
      - staff-network

volumes:
  mongodb_volume:
