version: '3.8'

networks:
  staff-network:
    driver: bridge

services:
  api: 
    image: node:alpine
    build:
      context: ./backend
      dockerfile: ./backend/Dockerfile
    volumes: 
      - .:/usr/src/app
    working_dir: /usr/src/app/backend  
    ports:
      - '3000:3000'  
    networks:
      - staff-network  
    depends_on:
      - api_mongo  
    # command: npm install && migrate-mongo up && node server  
    entrypoint: [ "/usr/src/app/backend/wait-for.sh", "api_mongo:27017", "--", "/usr/src/app/backend/start.sh" ]
    environment:
      - API_ADDR=http://api:3000
      - MONGO_URL=mongodb://api_mongo:27017/staff

  api_mongo:
    image: mongo:latest
    volumes:
      - mongodb_volume:/data/db
    ports:
      - '27017:27017'
    networks:
      - staff-network

volumes:
  mongodb_volume:
